import React from "react";

const languageDictionary = {
  Directing: { pt: "Direção" },
  Writing: { pt: "Roteiro/Escrita" },
  Production: { pt: "Produção" },
  Sound: { pt: "Som" },
  Camera: { pt: "Fotografia" },
  Art: { pt: "Arte/Design de Produção" },
  Editing: { pt: "Edição" },
  "Costume & Make-Up": { pt: "Figurino e Maquiagem" },
  Crew: { pt: "Equipe/Técnica" },
  "Visual Effects": { pt: "Efeitos Visuais" },
  Lighting: { pt: "Iluminação" },
  Acting: { pt: "Atuação" },
  Self: { pt: "Ele(a) Mesmo" },
  self: { pt: "Ele(a) Mesmo" },
  Director: { pt: "Direção" },
  Producer: { pt: "Produção" },
  "Executive Producer": { pt: "Produção Executiva" },
  Screenplay: { pt: "Roteiro" },
  Writer: { pt: "Escritor(a)" },
  Story: { pt: "História" },
  "Original Music Composer": { pt: "Compositor(a) Original" },
  Characters: { pt: "Personagens" },
  Herself: { pt: "Ela Mesmo" },
  Himself: { pt: "Ele Mesmo" },
  "Upset Girl": { pt: "Garota Triste" },
  "Self - Panelist": { pt: "Painelista" },
  "Self - Conductor": { pt: "Maestro(a)" },
  "Self (Pianist)": { pt: "Ele Mesmo (Pianista)" },
  Pianist: { pt: "Pianista" },
  "Self - Composer (archive footage)": {
    pt: "Compositor (imagens de arquivo)",
  },
  Orchestrator: { pt: "Maestro" },
  Music: { pt: "Música" },
  Conductor: { pt: "Regente" },
  "Music Arranger": { pt: "Arranjador Musical" },
  "Main Title Theme Composer": {
    pt: "Compositor do Tema Principal da Abertura",
  },
  "Music Supervisor": { pt: "Supervisor Musical" },
  "Costume Design": { pt: "Figurinista" },
  Thanks: { pt: "Creditado" },
  "Makeup Artist": { pt: "Maquiagem" },
  "Makeup Department Head": { pt: "Chefe da Maquiagem" },
  "Key Makeup Artist": { pt: "Maquiador(a) Principal" },
  Hairstylist: { pt: "Cabeleireiro(a)" },
  "Makeup Supervisor": { pt: "Supervisor(a) de Maquiagem" },
  "Makeup Designer": { pt: "Design de Maquiagem" },
  "Makeup & Hair": { pt: "Maquiagem e Cabelo" },
  "Special Effects Makeup Artist": { pt: "Efeitos Especiais de Maquiagem" },
  "Makeup Effects": { pt: "Efeitos de Maquiagem" },
  Judge: { pt: "Juiz(a)" },
  "Self - Interviewee": { pt: "Entrevista" },
  "Self - Judge": { pt: "Juiz(a)" },
  "Director of Photography": { pt: "Diretor(a) de Fotografia" },
  "Camera Operator": { pt: "Operador(a) de Camera" },
  '"A" Camera Operator': { pt: "O Operador(a)de Camera" },
  Cinematography: { pt: "Diretor(a) de Fotografia" },
  "Self - Executive Producer": { pt: "Produtor(a) Executivo" },
  "Production Supervisor": { pt: "Supervisão de Produção" },
  "Associate Producer": { pt: "Produção Associada" },
  "Co-Executive Producer": { pt: "Co Produtor(a) Executivo(a)" },
  "Self - Editor": { pt: "Edição" },
  "Self – Interviewee": { pt: "Entrevista" },
  "Assistant Director": { pt: "Assistente de Direção" },
  Editor: { pt: "Editor(a)" },
  "Supervising Film Editor": { pt: "Supervisão de Edição" },
  "Consulting Producer": { pt: "Consultoria de Produção" },
  "Production Design": { pt: "Design de Produção" },
  "Art Direction": { pt: "Direção de Arte" },
  "Sound Designer": { pt: "Designer de Som" },
  "Supervising Sound Editor": { pt: "Supervisão de Edição de Som" },
  "Sound Re-Recording Mixer": { pt: "Mixagem de Som" },
  "Additional Sound Re-Recording Mixer": { pt: "Adicional a Mixagem de Som" },
  Som: { pt: "Efeitos Sonoros" },
  "Sound Effects": { pt: "Efeitos Sonoros" },
  "Sound Mixer": { pt: "Mixagem de Som" },
  "Music Producer": { pt: "Produção Musical" },
  "Music Consultant": { pt: "Consultoria Musical" },
  "Music Score Producer": { pt: "Produção de Trilha Sonora" },
  Musician: { pt: "Musicista" },
  "Executive Music Producer": { pt: "Produção Executiva Musical" },
  "Additional Music": { pt: "Musica Adicional" },
  "Himself - Actor & Director": { pt: "Direção e Atuação" },
  "Self / Rocky Balboa (archive footage)": { pt: "Archivo próprio" },
  Choreographer: { pt: "Coreagrafia" },
  Creator: { pt: "Criação" },
  "Self - Guest": { pt: "Convidado(a)" },
  "Self (archive footage)": { pt: "Arquivo Pessoal" },
  "Self (uncredited)": { pt: "Ele(a) Mesmo" },
  himself: { pt: "Ele Mesmo" },
  "Self - After Party Guest": { pt: "Convidado(a) pós festa" },
  Extra: { pt: "Figurante" },
  "Self - Host": { pt: "Ele(as) Mesmo" },
  "annoying guy in van": { pt: "Cara Chato da Van" },
  "(archive footage)": { pt: "Arquivo Pessoal" },
  "Self - Filmmaker (archive footage)": { pt: "Filmagens de Arquivo Pessoal" },
  "Man in Electric Wheelchair (uncredited)": {
    pt: "Homen na Cadeira de Rodas Elétrica",
  },
  "Self (archive footage) (uncredited)": { pt: "Arquivo pessoal" },
  "Cook County Assessor's Office Clerk": {
    pt: "Escriturário do Escritório do Avaliador do Condado de Cook",
  },
  "Alien on TV Monitor (uncredited)": { pt: "Alen no Monitor de TV" },
  "Guest at David Aames' Party (uncredited)": {
    pt: "Convidado Na Festa de David Aames",
  },
  "Popcorn-Eating Man (uncredited)": { pt: "Homem Comendo Pipoca" },
  "Tourist at Airport (uncredited)": { pt: "Turista No Aeroporto" },
  "Steven Spielberg / Famous Director (Austinpussy)": { pt: "Ele Mesmo" },
  'Self - Director "Close Encounters" (archive footage)': { pt: "Ele Mesmo" },
  "Self - Producer, Writer, Director": { pt: "Produção, Roteiro, Direção" },
  "Creative Consultant": { pt: "Consultor Criativo" },
  Idea: { pt: "Idéia" },
  "Original Film Writer": { pt: "Escritor(a ) Da Ideia Original" },
  "Production Manager": { pt: "Gerente de Produção" },
  Presenter: { pt: "Apresentador" },
  "Himself (Archive Footage) (Voice)": { pt: "Ele Mesmo - Voz" },
  "Himself (archive)": { pt: "Ele Mesmo" },
  "Self - Filmmaker": { pt: "Cineasta" },
  "Party Guest": { pt: "Covidado(a) a Festa" },
  "Self - Musical Guest": { pt: "Convidado(a) Musical" },
  "Self - Host / Musical Guest": {
    pt: "Apresentador(a) e Convidado(a) Musical",
  },
  "Self - Host & Musical Guest": {
    pt: "Apresentador(a) e Convidado(a) Musical",
  },
  "Self - Presenter": { pt: "Apresentador(a)" },
  Songs: { pt: "Musicas" },
};

const TranslateProfile = ({ text, language }) => {
  const translate = (text) => {
    return languageDictionary[text]?.[language] || text;
  };
  return <span>{translate(text)}</span>;
};

export default TranslateProfile;
